# Conexion a la base de datos de Supabase (Puerto 6543 para modo Transaction)
spring.datasource.url=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.edjsxhzyaoachsivbmyv
spring.datasource.password=${DB_PASSWORD}

# Forzar el Driver de Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de Hibernate y JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Habilitar inicialización de datos con scripts personalizados
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Script en línea para crear al Veterinario de prueba automáticamente
spring.sql.init.data-locations=inline://INSERT INTO usuarios (id, dni, email, nombre_completo, password, telefono, rol) VALUES (99, '9999', 'vet@test.com', 'Veterinario Oficial', '123456', '2210000', 'VETERINARIO'); INSERT INTO veterinarios (usuario_id, matricula, es_administrador) VALUES (99, 'MAT-UTN-2026', true);