# 1. Configuración de la base de datos local en memoria (H2)
spring.datasource.url=jdbc:h2:mem:veturnosdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 2. Configuración de Hibernate y JPA para desarrollo local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Habilitar la inicialización automática con nuestro archivo data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always